#
# common UpCloud golangci-lint configuration
#

linters:
  #
  # we use a custom set of linters, so disable all and enable one-by-one
  #
  disable-all: true
  #
  # run golangci-lint linters or see https://golangci-lint.run/usage/linters/ for a list of all linters
  #
  # please keep these sorted alphabetically
  #
  enable:
    - asciicheck # not enabled in our initial configuration, proposal: ENABLE
    # - bodyclose # enabled in our initial configuration, proposal: DISABLE
    #? - cyclop # not enabled in our initial configuration, proposal: NOT SURE - consider the options
    - deadcode # enabled by default, proposal: KEEP
    # - depguard # enabled in our initial configuration, proposal: DISABLE
    - dogsled # enabled in our initial configuration, proposal: leaning KEEP
    - dupl # not enabled in our initial configuration, proposal: ENABLE
    - durationcheck # not enabled in our initial configuration, proposal: ENABLE
    - errcheck # enabled by default, proposal: KEEP
    - errname # not enabled in our initial configuration, proposal: ENABLE
    - errorlint # not enabled in our initial configuration, proposal: ENABLE
    - exhaustive # not enabled in our initial configuration, proposal: ENABLE
    # - exhaustivestruct # not enabled in our initial configuration, proposal: DO NOT ENABLE
    - exportloopref # not enabled in our initial configuration, proposal: ENABLE
    ## - forbidigo # not enabled in our initial configuration, proposal: ENABLE
    ## - forcetypeassert # not enabled in our initial configuration, proposal: ENABLE
    #? - funlen # not enabled in our initial configuration, proposal: NOT SURE
    #? - gci # not enabled in our initial configuration, proposal: NOT SURE
    # - gochecknoglobals # not enabled in our initial configuration, proposal: DO NOT ENABLE
    # - gochecknoinits # not enabled in our initial configuration, proposal: DO NOT ENABLE
    #? - gocognit # not enabled in our initial configuration, proposal: NOT SURE - consider the options
    - goconst # enabled in our initial configuration, proposal: KEEP
    ## - gocritic # enabled in our initial configuration, proposal: KEEP
    #? - gocyclo # not enabled in our initial configuration, proposal: NOT SURE - consider the options
    ## - godot # not enabled in our initial configuration, proposal: ENABLE
    #? - godox # not enabled in our initial configuration, proposal: NOT SURE - consider the argument made
    # - goerr113 # not enabled in our initial configuration, proposal: DO NOT ENABLE
    # - gofmt # enabled in our initial configuration, proposal: DISABLE, use gofumpt instead
    ## - gofumpt # not enabled in our initial configuration, proposal: ENABLE
    # - goheader # not enabled in our initial configuration, proposal: DO NOT ENABLE
    # - goimports # enabled in our initial configuration, proposal: DISABLE, use gci instead
    # - golint # deprecated
    #? - gomnd # not enabled in our initial configuration, proposal: NOT SURE
    #? - gomoddirectives # not enabled in our initial configuration, proposal: NOT SURE - clarify dbaas need + implications
    # - gomodguard # not enabled in our initial configuration, proposal: DO NOT ENABLE
    - goprintffuncname # enabled in our initial configuration, proposal: KEEP
    ## - gosec # enabled in our initial configuration, proposal: KEEP
    - gosimple # enabled by default, proposal: KEEP
    - govet # enabled by default, proposal: KEEP
    ## - ifshort # not enabled in our initial configuration, proposal: ENABLE
    - importas # not enabled in our initial configuration, proposal: ENABLE
    - ineffassign # enabled by default
    # - interfacer # deprecated
    #? - lll # not enabled in our initial configuration, proposal: NOT SURE
    ## - makezero # not enabled in our initial configuration, proposal: ENABLE
    # - maligned # deprecated
    - misspell # enabled in our initial configuration, proposal: KEEP
    - nakedret # enabled in our initial configuration, proposal: KEEP
    #? - nestif # not enabled in our initial configuration, proposal: NOT SURE
    ## - nilerr # not enabled in our initial configuration, proposal: ENABLE
    # - nlreturn # not enabled in our initial configuration, proposal: DO NOT ENABLE, prefer whitespace
    - noctx # not enabled in our initial configuration, proposal: ENABLE
    - nolintlint # enabled in our initial configuration, proposal: KEEP
    ## - paralleltest # not enabled in our initial configuration, proposal: ENABLE
    ## - prealloc # not enabled in our initial configuration, proposal: ENABLE
    - predeclared # not enabled in our initial configuration, proposal: ENABLE
    #? - promlinter # not enabled in our initial configuration, proposal: NOT SURE - do we need this?
    - revive # enabled in our initial configuration, proposal: KEEP
    - rowserrcheck # enabled in our initial configuration, proposal: KEEP or DISABLE if not required any more
    # - scopelint # deprecated
    - sqlclosecheck # not enabled in our initial configuration, proposal: ENABLE
    - staticcheck # enabled by default, proposal: KEEP
    - structcheck # enabled by default, proposal: KEEP
    - stylecheck # enabled in our initial configuration, proposal: NOT SURE - debatable style
    # - tagliatelle # not enabled in our initial configuration, proposal: DO NOT ENABLE
    ## - testpackage # not enabled in our initial configuration, proposal: ENABLE
    ## - thelper # not enabled in our initial configuration, proposal: ENABLE
    ## - tparallel # not enabled in our initial configuration, proposal: ENABLE
    - typecheck # enabled by default, proposal: KEEP
    - unconvert # enabled in our initial configuration, proposal: KEEP
    #? - unparam # enabled in our initial configuration, proposal: NOT SURE
    - unused # enabled by default, proposal: KEEP
    - varcheck # enabled by default, proposal: KEEP
    - wastedassign # not enabled in our initial configuration, proposal: ENABLE
    - whitespace # enabled in our initial configuration, proposal: KEEP
    #? - wrapcheck # not enabled in our initial configuration, proposal: NOT SURE - a lot of work to enable but good reasoning
    # - wsl # not enabled in our initial configuration, proposal: DO NOT ENABLE, prefer whitespace
issues:
  exclude:
    - "var-naming: .*should be.*"
    - "var-naming: don't use an underscore in package name"
linters-settings:
  stylecheck:
    checks: [ "all", "-ST1003" ]
  gomnd:
      settings:
        mnd:
          ignored-functions:
            - strconv.Parse*