version: "2"
linters:
  default: none
  # Run `golangci-lint linters` to see the list of all linters
  # Please keep them sorted alphabetically
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - dogsled
    - errcheck
    - goconst
    - gomoddirectives
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    goconst:
      min-len: 5
    govet:
      enable:
        - nilness
    predeclared:
      ignore:
        - new
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
