name: Terraform

on:
  pull_request:
    paths:
      - .github/workflows/acctest.yml
      - .github/workflows/terraform.yml
      - go.mod
      - go.sum
      - GNUmakefile
      - internal/**
      - .github/acctest-path-mapping.json
      - scripts/acctest-groups-from-diff.jq
      - scripts/acctest-groups-from-diff.sh
      - upcloud/**

jobs:
  Test:
    uses: ./.github/workflows/acctest.yml
    with:
      tool: terraform
    secrets: inherit
